### PR TITLE
Fixes iterator helpers when interacting with other polyfills

### PR DESCRIPTION
**Pull request by mhassan1**
This PR fixes iterator helpers when loaded alongside other polyfills (e.g. `String.prototype.@@iterator`). It is a follow-up to https://github.com/mrhenry/polyfill-library/pull/76.

### CODE REVIEW

**Comment by romainmenke** [comment]
IE is still failing, but might also be a browserstack issue: https://github.com/mrhenry/polyfill-library/actions/runs/11454689367/job/31934817539
I've noticed that IE has more and more intermittent issues on browserstack.

**Comment by mhassan1** [comment]
> IE is still failing, but might also be a browserstack issue: https://github.com/mrhenry/polyfill-library/actions/runs/11454689367/job/31934817539 I've noticed that IE has more and more intermittent issues on browserstack.

I can replicate that issue locally. When I look in BrowserStack, I see `Browser could not be launched for the session`. Here are some docs about that: https://www.browserstack.com/docs/automate/selenium/error-codes/browserstack-failed-to-start-browser. Maybe we should open a support ticket.

Any comments on this PR?

**Comment by mhassan1** [comment]
@romainmenke Please take a look, if you have some time.

**Comment by romainmenke** [comment]
Haven't had much time :/
I will review this in the coming days

**Review by romainmenke — APPROVED** [review]
Thank you. LGTM 👍

----

Sorry it took a while to get to this :)

**Pull request merged**
