### PR TITLE
Bumps `webdriverio` to latest, adds `isRetryableError` utility, reduces test flakiness

### PR DESCRIPTION
**Pull request by mhassan1**
This PR bumps `webdriverio` to latest, which may help with CI flakiness. It also adds an `isRetryableError` utility that will retry jobs on the following errors:
1. [Failed to create session](https://github.com/mrhenry/polyfill-library/actions/runs/12128696356/job/33818351286)
```txt
Error: Failed to create session.
WebDriverError: This operation was aborted when running "https://hub-cloud.browserstack.com/wd/hub/session" with method "POST" and args "{"capabilities":{"alwaysMatch":{"bstack:options":{"sessionName":"build:null_2024-12-02T23:30:01.135Z","projectName":"polyfill-library","local":true,"video":true,"debug":true,"consoleLogs":"errors","networkLogs":true},"browserName":"chrome","browserVersion":"102.0","webSocketUrl":true},"firstMatch":[{}]}}"
    at startWebDriverSession (file:///home/runner/work/polyfill-library/polyfill-library/node_modules/webdriver/build/index.js:853:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async _WebDriver.newSession (file:///home/runner/work/polyfill-library/polyfill-library/node_modules/webdriver/build/index.js:1547:41)
    at async remote (file:///home/runner/work/polyfill-library/polyfill-library/node_modules/webdriverio/build/index.js:7228:20)
    at async TestJob.run (/home/runner/work/polyfill-library/polyfill-library/test/polyfills/test-job.js:102:19)
```
2. [An unknown server-side error occurred while processing the command](https://github.com/mrhenry/polyfill-library/actions/runs/12148384546/job/33876735290)
```txt
unknown error: WebDriverError: An unknown server-side error occurred while processing the command. when running "window" with method "DELETE"
    at FetchRequest._request (file:///home/runner/work/polyfill-library/polyfill-library/node_modules/webdriver/build/node.js:1652:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Browser.wrapCommandFn (file:///home/runner/work/polyfill-library/polyfill-library/node_modules/@wdio/utils/build/index.js:884:23)
    at async TestJob.run (/home/runner/work/polyfill-library/polyfill-library/test/polyfills/test-job.js:175:4)
```

It also includes https://github.com/mrhenry/polyfill-library/pull/90, which further reduces test flakiness.

### CODE REVIEW

**Comment by mhassan1** [comment]
@romainmenke I didn't see any `Failed to create session.` error logs in the [run](https://github.com/mrhenry/polyfill-library/actions/runs/12147333445) on this PR, so maybe the `webdriverio` upgrade solved that, or maybe we just got lucky 😄. Anyway, this PR should be safe to merge.

**Comment by romainmenke** [comment]
Thank you for spending time on this @mhassan1 🙇 

Should we also retry on this error:

https://github.com/mrhenry/polyfill-library/actions/runs/12148384546/job/33876735290

```
WebDriverError: An unknown server-side error occurred while processing the command. when running "window" with method "DELETE"
```

Or possibly extending the sharding of tests to IE 10 and IE 11?
I think the window becomes unresponsive at some point when running all the tests with also all the polyfills loaded.

It is mostly important that we test each feature individually with every other polyfill present. Not so much that we test all features in one go.

**Comment by mhassan1** [comment]
@romainmenke I've created an `isRetryableError` utility, and I've added that error to the list.

**Comment by romainmenke** [comment]
Nice!

https://github.com/mrhenry/polyfill-library/actions/runs/12153971340/job/33892964196

Maybe this one too?

`WebDriverError: The operation was aborted due to timeout when running "execute/sync" with method "POST"`

**Comment by mhassan1** [comment]
> Maybe this one too?

Added.

**Pull request merged**
